sudo: false
language: node_js
node_js:
  - '14.16.0'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - cd myapp
  - npm update
install:
  - npm install
script:
  - npm run test -- --coverage
